import normalize from "./normalizeState";

export default {
  [normalize("Andaman & Nicobar Island")]: "andamannicobar.json",
  [normalize("Andhra Pradesh")]: "andhrapradesh.json",
  [normalize("Arunachal Pradesh")]: "arunachalpradesh.json",
  [normalize("Assam")]: "assam.json",
  [normalize("Bihar")]: "bihar.json",
  [normalize("Chhattisgarh")]: "chhattisgarh.json",
  [normalize("NCT of Delhi")]: "delhi.json",
  [normalize("Goa")]: "goa.json",
  [normalize("Gujarat")]: "gujarat.json",
  [normalize("Haryana")]: "haryana.json",
  [normalize("Himachal Pradesh")]: "himachalpradesh.json",
  [normalize("Jammu & Kashmir")]: "jammukashmir.json",
  [normalize("Jharkhand")]: "jharkhand.json",
  [normalize("Karnataka")]: "karnataka.json",
  [normalize("Kerala")]: "kerala.json",
  [normalize("Lakshadweep")]: "lakshadweep.json",
  [normalize("Madhya Pradesh")]: "madhyapradesh.json",
  [normalize("Maharashtra")]: "maharashtra.json",
  [normalize("Manipur")]: "manipur.json",
  [normalize("Meghalaya")]: "meghalaya.json",
  [normalize("Mizoram")]: "mizoram.json",
  [normalize("Nagaland")]: "nagaland.json",
  [normalize("Odisha")]: "odisha.json",
  [normalize("Punjab")]: "punjab.json",
  [normalize("Rajasthan")]: "rajasthan.json",
  [normalize("Sikkim")]: "sikkim.json",
  [normalize("Tamil Nadu")]: "tamilnadu.json",
  [normalize("Telangana")]: "telangana.json",
  [normalize("Tripura")]: "tripura.json",
  [normalize("Uttarakhand")]: "uttarakhand.json",
  [normalize("Uttar Pradesh")]: "uttarpradesh.json",
  [normalize("West Bengal")]: "westbengal.json",
};